app:
  name: authentication
  description: "authentication"
  version: "1.0.0"
  base-path: /api

desenv:
  sql_console: true

spring:
  profiles: development
  application.name: ${app.name}
  main.banner-mode: "off"
  data.rest.base-path: ${app.base-path}
  jpa:
    default_schema: public
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        show_sql: ${desenv.sql_console}
        format_sql: ${desenv.sql_console}
        dialect: ${spring.jpa.database-platform}
        temp.use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true

  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.200.140:5432/edimar
    username: desenv
    password: desenv

    hikari:
      maximum-pool-size: 2
      minimum-idle: 2
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      connection-test-query: SELECT 1
      data-source-properties:
         cachePrepStmts: true
         prepStmtCacheSize: 250
         prepStmtCacheSqlLimit: 2048
         useServerPrepStmts: true
         useLocalSessionState: true
         rewriteBatchedStatements: true
         cacheResultSetMetadata: true
         cacheServerConfiguration: true
         elideSetAutoCommits: true
         maintainTimeStats: false

server:
  port: 8090
  servlet:
    context-path: /
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,
                text/xml,
                text/plain,
                text/css,
                text/javascript,
                application/javascript,
                application/json,
                application/xml,
                application/pdf,
                image/png,
                image/jpeg,
                image/svg+xml